{* The interface texts of the layout editor (javascript/netgen-layouts.js), translated here
   and handed to the bundle as window.nglayoutsSpaI18n, keyed by the English text; the
   bundle looks them up with nglT() / nglTh() and falls back to the English text. *}
<script>
window.nglayoutsSpaI18n = {ldelim}
    'A new version of this site is available. Load it?': '{"A new version of this site is available. Load it?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'There could be unsaved changes. Are you sure you want to leave?': '{"There could be unsaved changes. Are you sure you want to leave?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Refresh': '{"Refresh"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Not allowed': '{"Not allowed"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'You don\'t have permission to edit this layout.': '{"You don't have permission to edit this layout."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'OK': '{"OK"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Session timeout': '{"Session timeout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Your session has timed out. Please hit the refresh button to reload the application.': '{"Your session has timed out. Please hit the refresh button to reload the application."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Layout does not exist': '{"Layout does not exist"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Layout you are trying to edit does not exist.': '{"Layout you are trying to edit does not exist."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Back to admin': '{"Back to admin"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Something went wrong!': '{"Something went wrong!"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    '%language (Main)': '{"%language (Main)"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Edit layout': '{"Edit layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Edit master of layout': '{"Edit master of layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Choose layout zone': '{"Choose layout zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Link layout': '{"Link layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'What would you like to do with the draft?': '{"What would you like to do with the draft?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Discard': '{"Discard"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Publish layout': '{"Publish layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Publish and continue editing': '{"Publish and continue editing"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Save draft and close': '{"Save draft and close"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Hidden in CMS': '{"Hidden in CMS"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Edit in CMS': '{"Edit in CMS"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Set position': '{"Set position"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Override item view type': '{"Override item view type"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Remove': '{"Remove"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Save': '{"Save"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Cancel': '{"Cancel"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Override slot view type': '{"Override slot view type"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Delete %kind': '{"Delete %kind"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Move %kind': '{"Move %kind"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Loading': '{"Loading"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    '+ Add items': '{"+ Add items"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Remove all manual items': '{"Remove all manual items"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'An error occurred and we\'re not sure why.': '{"An error occurred and we're not sure why."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Please, send the error details below to developers with the description of what you were doing when the error occurred to help fix it.': '{"Please, send the error details below to developers with the description of what you were doing when the error occurred to help fix it."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Error details': '{"Error details"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Back': '{"Back"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Apply': '{"Apply"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Name:': '{"Name:"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Updated at:': '{"Updated at:"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'New draft': '{"New draft"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Edit existing': '{"Edit existing"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Create layout': '{"Create layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Trash': '{"Trash"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select a block to access its properties.': '{"Select a block to access its properties."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'You can link a zone in the layout by pointing it to a zone in the shared layout. Blocks from the shared layout zone will then be displayed in the linked zone.': '{"You can link a zone in the layout by pointing it to a zone in the shared layout. Blocks from the shared layout zone will then be displayed in the linked zone."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Multiple zones in this layout can be linked to zones from different shared layouts.': '{"Multiple zones in this layout can be linked to zones from different shared layouts."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Use the dropdown menu to select a shared layout you want to preview and then select a desired target zone to create a link.': '{"Use the dropdown menu to select a shared layout you want to preview and then select a desired target zone to create a link."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Unlink zone from layout_id: "%layout" and zone_id: "%zone"': '{'Unlink zone from layout_id: "%layout" and zone_id: "%zone"'|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Edit linked layout': '{"Edit linked layout"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Choose zone': '{"Choose zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Link zone': '{"Link zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Choose a zone you wish to link': '{"Choose a zone you wish to link"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Choose one of the shared layouts and then select a target zone': '{"Choose one of the shared layouts and then select a target zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'This zone is already linked with': '{"This zone is already linked with"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Layout:': '{"Layout:"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Zone:': '{"Zone:"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Update link': '{"Update link"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Choose different zone': '{"Choose different zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Unlink': '{"Unlink"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select zone': '{"Select zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Move block': '{"Move block"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Delete block': '{"Delete block"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to delete the block? This cannot be undone.': '{"Are you sure you want to delete the block? This cannot be undone."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Delete': '{"Delete"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Revert block': '{"Revert block"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to revert the block to its published version? This cannot be undone.': '{"Are you sure you want to revert the block to its published version? This cannot be undone."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Revert': '{"Revert"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Block successfully duplicated.': '{"Block successfully duplicated."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Exit': '{"Exit"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Remove all added items': '{"Remove all added items"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to remove all added items? This cannot be undone.': '{"Are you sure you want to remove all added items? This cannot be undone."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Delete item': '{"Delete item"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to delete this item? This cannot be undone.': '{"Are you sure you want to delete this item? This cannot be undone."|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'New position must be larger than 0': '{"New position must be larger than 0"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'New position shouldn\'t be larger than position of the last item in collection (%count)': '{"New position shouldn't be larger than position of the last item in collection (%count)"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Skipping %count manual item': '{"Skipping %count manual item"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Skipping %count manual items': '{"Skipping %count manual items"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Skipping %count item': '{"Skipping %count item"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Skipping %count items': '{"Skipping %count items"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Skipping %count items, %manual of them manual': '{"Skipping %count items, %manual of them manual"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    '%count manual item out of range': '{"%count manual item out of range"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    '%count manual items out of range': '{"%count manual items out of range"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Cache clearing': '{"Cache clearing"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Automatic cache clear for this site is turned off. Do you want to clear caches after publish?': '{"Automatic cache clear for this site is turned off. Do you want to clear caches after publish?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Clear caches': '{"Clear caches"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Do not clear caches': '{"Do not clear caches"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Discard changes': '{"Discard changes"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to discard your changes to the layout draft?': '{"Are you sure you want to discard your changes to the layout draft?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    '%name - Exponential Layouts': '{"%name - Exponential Layouts"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Link zone with shared layout zone': '{"Link zone with shared layout zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Unlink zone': '{"Unlink zone"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Are you sure you want to unlink this zone?': '{"Are you sure you want to unlink this zone?"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Go to today': '{"Go to today"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Clear selection': '{"Clear selection"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Close the picker': '{"Close the picker"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select Month': '{"Select Month"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Previous Month': '{"Previous Month"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Next Month': '{"Next Month"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select Year': '{"Select Year"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Previous Year': '{"Previous Year"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Next Year': '{"Next Year"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select Decade': '{"Select Decade"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Previous Decade': '{"Previous Decade"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Next Decade': '{"Next Decade"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Previous Century': '{"Previous Century"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Next Century': '{"Next Century"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Pick Hour': '{"Pick Hour"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Increment Hour': '{"Increment Hour"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Decrement Hour': '{"Decrement Hour"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Pick Minute': '{"Pick Minute"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Increment Minute': '{"Increment Minute"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Decrement Minute': '{"Decrement Minute"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Pick Second': '{"Pick Second"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Increment Second': '{"Increment Second"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Decrement Second': '{"Decrement Second"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Toggle Period': '{"Toggle Period"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Select Time': '{"Select Time"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Block options': '{"Block options"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Block options (nothing selected)': '{"Block options (nothing selected)"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}',
    'Close the properties panel': '{"Close the properties panel"|i18n( 'design/standard/explayouts_ui_api/spa' )|wash( javascript )}'
{rdelim};
</script>
